// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package cn.pxwell.netty.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.pxwell.netty.proto.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 1;</code>
   */
  String getRealname();
  /**
   * <code>string realname = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
