// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package cn.pxwell.netty.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:cn.pxwell.netty.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .cn.pxwell.netty.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<StudentResponse>
      getStudentResponseList();
  /**
   * <code>repeated .cn.pxwell.netty.proto.StudentResponse studentResponse = 1;</code>
   */
  StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .cn.pxwell.netty.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .cn.pxwell.netty.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends StudentResponseOrBuilder>
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .cn.pxwell.netty.proto.StudentResponse studentResponse = 1;</code>
   */
  StudentResponseOrBuilder getStudentResponseOrBuilder(
          int index);
}
